# Generated by Django 4.2.9 on 2024-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='videos',
        ),
    ]
