# Generated by Django 4.2.9 on 2024-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='مجهول', max_length=100, verbose_name='الاسم'),
        ),
    ]
