# Generated by Django 4.2.9 on 2024-01-14 21:35

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_item_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.DeleteModel(
            name='videos',
        ),
    ]
